services:
  supervisor:
    build:
      context: ./supervisor
      dockerfile: Dockerfile
    container_name: supervisor
    ports:
      - "8080:8080"
    networks:
      - supervisor-network

networks:
  supervisor-network:
    driver: bridge
